############################################################
# +------------------------------------------------------+ #
# |                      Information                     | #
# +------------------------------------------------------+ #
############################################################

# This is the configuration file for EssentialsX-GUI.

# If you need help with the configuration of the plugin,
# you can join our discord server at: https://discord.gg/fSzK79TAYf

# For more information about how to configure EssentialsX-GUI,
# check our Wiki at: https://sniper-tvmc.gitbook.io/essentialsx-gui/configuration/main-configuration

############################################################
# +------------------------------------------------------+ #
# |                        General                       | #
# +------------------------------------------------------+ #
############################################################

general:

  # Please do not change this value as it may cause the file to be reset.
  # Default: "1.3"
  configVersion: "1.3"

  # If you want to see a detailed loading message when the plugin is loading, set this to true. (Also works for unloading)
  # Default: true
  detailedLoading: true

  # Do you want to check for updates of the plugin?
  # Default: true
  checkForUpdates: true


  modules:

    homes:

      # Set this to true if you want to use the homes features.
      # This will allow players to access the homes GUI.
      # Default: true
      enabled: true


      # Decide how players can create a home.
      # Ways available: "CHAT", "ANVIL"
      createNewHomeEntryType: "CHAT"


      # Decide how players can search for a home.
      # Ways available: "CHAT", "ANVIL"
      searchHomeEntryType: "ANVIL"


      # Decide how players can change the display name of a home.
      # Ways available: "CHAT", "ANVIL"
      changeHomeDisplayNameEntryType: "CHAT"


      # Decide how players can change the icon of a home.
      # Ways available: "CHAT", "ANVIL", "GUI", "ITEM_IN_HAND"
      changeHomeIconEntryType: "GUI"

      # If you set the changeHomeIconEntryType to "GUI", you must set the materials available in the GUI here.
      changeHomeIconMaterialList: ["STONE", "COBBLESTONE", "DIRT", "IRON_ORE", "DIAMOND_BLOCK", "SPONGE", "ANVIL",
                                   "QUARTZ_BLOCK", "COOKED_BEEF", "APPLE", "BREAD", "WHEAT", "BOW", "IRON_SWORD",]


      # Decide how players can delete a home.
      # Ways available: "CHAT", "ANVIL"
      deleteHomeEntryType: "CHAT"

    kits:

      # Set this to true if you want to use the kits features.
      # This will allow players to access the kits GUI.
      # Default: true
      enabled: true


      # Decide how players can create a kit.
      # Ways available: "CHAT", "ANVIL"
      createNewKitNameEntryType: "CHAT"


      # Decide how players can create a kit.
      # Ways available: "CHAT", "ANVIL"
      createNewKitDelayEntryType: "CHAT"


      # Decide how players can search for a kit.
      # Ways available: "CHAT", "ANVIL"
      searchKitEntryType: "ANVIL"


      # Decide how players can change the display name of a kit.
      # Ways available: "CHAT", "ANVIL"
      changeKitDisplayNameEntryType: "CHAT"


      # Decide how players can change the icon of a kit.
      # Ways available: "CHAT", "ANVIL", "GUI", "ITEM_IN_HAND"
      changeKitIconEntryType: "GUI"

      # If you set the changeKitIconEntryType to "GUI", you must set the materials available in the GUI here.
      changeKitIconMaterialList: ["STONE", "COBBLESTONE", "DIRT", "IRON_ORE", "DIAMOND_BLOCK", "SPONGE", "ANVIL",
                                  "QUARTZ_BLOCK", "COOKED_BEEF", "APPLE", "BREAD", "WHEAT", "BOW", "IRON_SWORD",]


      # Decide how players can delete a kit.
      # Ways available: "CHAT", "ANVIL"
      deleteKitEntryType: "CHAT"


  # Default text of input when using anvil way to enter text.
  # Default: "Type here"
  anvilTypeHereText: "Type here"


  # Minimum and maximum length for names entered by players.
  # ⚠️ Warning: Payers can bypass these limits if they use the defaults commands of EssentialsX.
  #             This only applies to names and not to display names, icons, etc.
  # Default: min = 3, max = 32
  minNameLength: 3
  maxNameLength: 32


  # Set this to true if you want to open the kit admin view by default when the /kit command is performed for players
  # with permission to see the admin view.
  # Default: false
  openKitAdminViewByDefault: false

############################################################
# +------------------------------------------------------+ #
# |                        Sounds                        | #
# +------------------------------------------------------+ #
############################################################

sounds:

  # Set this to true if you want to enable all sounds in the plugin.
  # To disable a specific sound, you can leave the sound name blank.
  # Default: true
  enabled: true


  # Warning: This section should follow values listed on this website:
  # - https://helpch.at/docs/1.21.5/org/bukkit/Sound.html
  # Change '1.21.5' with your current Minecraft version.


  # The sound played when a player opens a GUI.
  # Default: "%%value_guiOpen%%"
  guiOpen: "%%value_guiOpen%%"

  # The sound played when a player clicks on a close item.
  # Default: "%%value_guiClose%%"
  guiClose: "%%value_guiClose%%"

  # The sound played when a player clicks on a back item.
  # Default: "%%value_guiBack%%"
  guiBack: "%%value_guiBack%%"

  # The sound played when a player clicks on an interactive item in the GUI.
  # Default: "%%value_guiClick%%"
  guiClick: "%%value_guiClick%%"

  # The sound played when a player changes the page in a paginated GUI.
  # Default: "%%value_guiPageChange%%"
  guiPageChange: "%%value_guiPageChange%%"


  # The sound played when a player completes an action.
  # Default: "%%value_actionSuccess%%"
  actionSuccess: "%%value_actionSuccess%%"

  # The sound played when a player cancels an action.
  # Default: "%%value_actionCanceled%%"
  actionCanceled: "%%value_actionCanceled%%"

  # The sound played when a player fails an action.
  # Default: "%%value_actionFailure%%"
  actionFailure: "%%value_actionFailure%%"

############################################################
# +------------------------------------------------------+ #
# |                      Permissions                     | #
# +------------------------------------------------------+ #
############################################################

permissions:

  admin:

    # Change the permission needed to receive a message when an update of the plugin is available.
    # Default: "essentialsxgui.admin.update"
    updateAlert: "essentialsxgui.admin.update"

  commands:

    # Change the permission needed to access to the EssentialsX-GUI command.
    # Default: "essentialsxgui.command.essentialsxgui"
    essentialsxgui: "essentialsxgui.command.essentialsxgui"

    # Change the permission needed to access to the EssentialsX-GUI debug command.
    # Default: "essentialsxgui.command.essentialsxgui.debug"
    debugArgument: "essentialsxgui.command.essentialsxgui.debug"


  guis:

    # Change the permission needed to access to the Kits GUI in admin mode.
    # Default: "essentialsx.gui.kits.admin"
    kitsAdminAccess: "essentialsxgui.kits.admin"

############################################################
# +------------------------------------------------------+ #
# |                        Storage                       | #
# +------------------------------------------------------+ #
############################################################

storage:

  # ⚠ Warning ⚠: Changing this value will migrate all your data to the new storage type,
  #              For example, if you change from SQLite to MySQL, your data will be migrated to MySQL database,
  #              so data (of the plugin) on your old MySQL database will be lost if you had any,
  #              and the SQLite database file will remain in the plugin folder with all current data and
  #              will not be used anymore. (Neither deleted, you can delete it manually if you want.)
  #
  # Choose the storage type you want to use to save data.
  # Available types: "SQLite" (local file), "MySQL", "MariaDB" (preferred over MySQL)
  # Default: "SQLite"
  type: "SQLite"

  mysql:

    # MySQL or MariaDB hostname (IP address or domain name).
    host: "localhost"

    # MySQL or MariaDB port.
    port: 3306

    # MySQL or MariaDB database name.
    database: "minecraft_database"

    # MySQL or MariaDB username.
    username: "minecraft_user"

    # MySQL or MariaDB password.
    password: ""

    # MySQL or MariaDB settings.
    # Warning: Do not change this if you don't know what you are doing.
    settings: "?useSSL=false&serverTimezone=UTC"

    # If you want to use a custom table prefix for the tables created by EssentialsX-GUI, set it here.
    tablePrefix: "exg_"