############################################################
# +------------------------------------------------------+ #
# |                     Informations                     | #
# +------------------------------------------------------+ #
############################################################

# This is the configuration file for EssentialsX-GUI.

# If you need help with the configuration of the plugin,
# you can join our discord server at: https://discord.gg/fSzK79TAYf

# For more information about how to configure EssentialsX-GUI,
# check our Wiki at: SOON

############################################################
# +------------------------------------------------------+ #
# |                        General                       | #
# +------------------------------------------------------+ #
############################################################

general:

  # Please do not change this value as it may cause the file to be reset.
  # Default: 1.0
  configVersion: "1.0"

  # If you want to see a detailed loading message when the plugin is loading, set this to true. (Also works for unloading)
  # Default: true
  detailedLoading: true


  modules:

    # Set this to true if you want to use the homes features.
    # This will allow players to access the homes GUI.
    # Default: true
    homes: true

    # Set this to true if you want to use the kits features.
    # This will allow players to access the kits GUI.
    # Default: true
    kits: true

############################################################
# +------------------------------------------------------+ #
# |                        Sounds                        | #
# +------------------------------------------------------+ #
############################################################

sounds:

  # Set this to true if you want to enable sounds in the plugin.
  # Default: true
  enabled: true


  # The sound played when a player opens a GUI.
    # Default: "CHEST_OPEN"
  guiOpen: "CHEST_OPEN"

  # The sound played when a player clicks on a close item.
  # Default: "CHEST_CLOSE"
  guiClose: "CHEST_CLOSE"

  # The sound played when a player clicks on a back item.
  # Default: "SHOOT_ARROW"
  guiBack: "SHOOT_ARROW"

  # The sound played when a player clicks on an interactive item in the GUI.
  # Default: "CHICKEN_EGG_POP"
  guiClick: "CHICKEN_EGG_POP"


  # The sound played when a player completes an action.
  # Default: "LEVEL_UP"
  actionSuccess: "LEVEL_UP"

  # The sound played when a player fails an action.
  # Default: "VILLAGER_NO"
  actionFailure: "VILLAGER_NO"

############################################################
# +------------------------------------------------------+ #
# |                      Permissions                     | #
# +------------------------------------------------------+ #
############################################################

permissions:

  commands:

    # Change the permission needed to access to the EssentialsX-GUI command.
    # Default: "essentialsxgui.command.essentialsxgui"
    essentialsxgui: "essentialsxgui.command.essentialsxgui"


  guis:

    # Change the permission needed to access to the Kits GUI in admin mode.
    # Default: "essentialsx.gui.kits.admin"
    kitsAdminAccess: "essentialsxgui.kits.admin"