main: fr.snipertvmc.essentialsxgui.Main


name: EssentialsX-GUI
description: GUI Addon for EssentialsX
website: https://github.com/SniperTVmc/EssentialsX-GUI/
author: Sniper_TVmc


version: ${project.version}
api-version: 1.13


depend:
  - Essentials


libraries:
  - "org.mariadb.jdbc:mariadb-java-client:3.5.6"


commands:


  essentialsXGUI:
    description: Main command for management of the plugin.
    aliases:
      - exg