package fr.snipertvmc.essentialsxgui.utilities.other;

import com.earth2me.essentials.CommandSource;
import com.earth2me.essentials.Essentials;
import com.earth2me.essentials.MetaItemStack;
import com.earth2me.essentials.libs.snakeyaml.external.biz.base64Coder.Base64Coder;
import fr.snipertvmc.essentialsxgui.utilities.ConsoleLogger;
import net.ess3.provider.SerializationProvider;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

@Deprecated(forRemoval = true)
public class EssentialsParser {


	// -------------------------------------------------- //

//	/**
//	 * <p><strong>WARNING:</strong> This method is based on internal EssentialsX logic, adapted from
//	 * the <code>Kit#expandItems</code> implementation. EssentialsX does <strong>not</strong> provide a stable public API
//	 * for parsing kit item strings, so this logic depends on internal structures that may change at any time.</p>
//	 *
//	 * <p><strong>Function purpose:</strong><br>
//	 * Converts raw item strings from a kit (as defined in <code>kits.yml</code>) into a list of Bukkit
//	 * <code>ItemStack</code> objects, without modifying inventories or triggering side effects (commands, economy, etc).</p>
//	 *
//	 * <p><strong>Use cases:</strong></p>
//	 * <ul>
//	 *     <li>Kit preview systems (GUI or CLI)</li>
//	 *     <li>Custom kit filters or permission checks</li>
//	 *     <li>Addon integration with EssentialsX kits</li>
//	 * </ul>
//	 *
//	 * <p><strong>Important:</strong></p>
//	 * <ul>
//	 *     <li>This function uses classes like <code>MetaItemStack</code> and <code>SerializationProvider</code> from EssentialsX internals.</li>
//	 *     <li>It is <strong>not officially supported</strong> by the EssentialsX team.</li>
//	 *     <li><strong>Breakage is possible</strong> in future EssentialsX updates. Always verify compatibility before releasing updates.</li>
//	 *     <li>EssentialsX is licensed under the GNU GPLv3. Ensure your plugin or addon is compliant.</li>
//	 * </ul>
//	 *
//	 * <p><strong>Disclaimer:</strong><br>
//	 * This function was generated by OpenAI's ChatGPT (with developer guidance) for educational and integration purposes.
//	 * The author of this plugin/addon is <strong>not responsible</strong> for the internal behavior or future changes of EssentialsX.
//	 * Always test thoroughly and maintain your own compatibility layer if needed.</p>
//	 */

	/** A similar method has already been implemented in EssentialsX-GUI :<br>
	 * {@link fr.snipertvmc.essentialsxgui.hooks.EssentialsHook#getKitItems(Player, String)}
	*/
	@Deprecated(since = "1.1.1", forRemoval = true)
	public static List<ItemStack> deserializeKitItems(Essentials essentials, List<String> items, CommandSender source) {

		List<ItemStack> itemList = new ArrayList<>();
		boolean allowUnsafe = essentials.getSettings().allowUnsafeEnchantments();

		for (String kitItem : items) {

			try {
				if (kitItem.startsWith("/") || kitItem.startsWith("$") || kitItem.matches("^[€$].*")) {
					continue;
				}

				ItemStack stack;

				if (kitItem.startsWith("@")) {
					SerializationProvider provider = essentials.provider(SerializationProvider.class);
					if (provider == null) {
						Bukkit.getLogger().warning("Impossible de lire un item Base64 dans un kit !");
						continue;
					}
					stack = provider.deserializeItem(Base64Coder.decodeLines(kitItem.substring(1)));

				} else {
					String[] parts = kitItem.split(" +");
					int amount = parts.length > 1 ? Integer.parseInt(parts[1]) : 1;

					ItemStack baseStack = essentials.getItemDb().get(parts[0], amount);
					if (baseStack.getType() == Material.AIR) {
						continue;
					}

					MetaItemStack metaStack = new MetaItemStack(baseStack);
					if (parts.length > 2) {
						metaStack.parseStringMeta(
								(source instanceof CommandSource cmdSource) ? cmdSource : null,
								allowUnsafe,
								parts,
								2,
								essentials
						);
					}

					stack = metaStack.getItemStack();
				}

				itemList.add(stack);

			} catch (Exception e) {
				ConsoleLogger.error("Failed to parse an item from kit: " + kitItem);
			}
		}

		return itemList;
	}


	// -------------------------------------------------- //
}
